from django.conf import settings
import boto
from boto.s3.key import Key
from django.core.mail import send_mail, EmailMessage
import pprint
from django.core.files.storage import default_storage
import os

FROM_VIAM_EMAIL = getattr(settings, "FROM_VIAM_EMAIL", None)
ENABLE_EMAIL_SANDBOX = getattr(settings, "ENABLE_EMAIL_SANDBOX", None)

def send_mail(subject, message, recipient_list, from_email=None, attachment=None ):
	html_message = True
	if ENABLE_EMAIL_SANDBOX is not None and ENABLE_EMAIL_SANDBOX == True:
		recipient_list = ['kunal.rachhoya@viamhealth.com','Narendra.Mudigal@viamhealth.com',]

	try:
		if from_email is None:
			from_email = FROM_VIAM_EMAIL
		email = EmailMessage(subject, message, from_email, recipient_list)

		if attachment is not None:
			
			LOCAL_PATH = settings.S3_LOCAL_DOWNLOAD_LOCATION

			conn = boto.connect_s3(settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
			key = conn.get_bucket(settings.AWS_STORAGE_BUCKET_NAME).get_key(attachment.get('url'))

			if os.path.exists(LOCAL_PATH+attachment.get('name')):
				os.remove(LOCAL_PATH+attachment.get('name'))
			key.get_contents_to_filename(LOCAL_PATH+attachment.get('name'))
			att = file(LOCAL_PATH+attachment.get('name'),'r')
			if att:
				email.attach(attachment.get('name'), att.read())
			else:
				pass
			
		if html_message:
		    email.content_subtype = 'html'
		email.send()
		return True
	except Exception as e:
		print '%s (%s)' % (e.message, type(e))
		return False

def signup_email(email):
	subject = 'Welcome to Viamhealth'
	message = 'You have signed up on Viamhealth.<br/> Your username = ' + str(email)
	send_mail(subject, message, [email])

def invite_new_email(invited, inviter, password):
	by_invited = ''
	
	if inviter.first_name is not None and str(inviter.first_name) != '':
		by_invited = 'by '+ str(inviter.first_name)
	email = invited.email
	subject = 'You have been invited to Viamhealth'
	message = 'You have invited to join Viamhealth ' + by_invited + '.<br/> Your username = ' + str(email) + '<br/> Your password = '+ password
	send_mail(subject, message, [email])

def invite_existing_email(invited, inviter):
	by_invited = ''
	
	if inviter.first_name is not None and str(inviter.first_name) != '':
		by_invited = 'by '+ str(inviter.first_name)
	email = invited.email
	subject = 'You have been invited to Viamhealth'
	message = 'You have invited to join Viamhealth ' + by_invited + '.<br/> Your username = ' + str(email)
	send_mail(subject, message, [email])

def forgot_password_email(user,password):
	email = user.email
	subject = 'Your new autogenerated password'
	message = 'Your new autogenerated password is '+password
	send_mail(subject, message, [email])

def share_user_email(invited, inviter, share_user):
	by_invited = ''
	
	if inviter.first_name is not None and str(inviter.first_name) != '':
		by_invited = 'by '+ str(inviter.first_name)

	shared_of = ''
	if share_user.first_name is not None and str(share_user.first_name) != '':
		shared_of = 'of '+ str(share_user.first_name)

	email = invited.email
	subject = 'Profile shared on Viamhealth'
	message = 'Profile ' + shared_of + ' have been shared with you ' + by_invited 
	inv_email = None
	if inviter.email is not None:
		inv_email = inviter.email
	send_mail(subject, message, [email], inv_email)

def share_healthfile_email(owner, email,att):
	
	email = email
	if owner.first_name is not None and owner.first_name != '':
		subject = owner.first_name + ' shared a file with you'
	else:
		subject = 'Find attached a file shared with you'

	message = 'File shared'
	inv_email = None
	if owner.email is not None:
		inv_email = owner.email
	
	send_mail(subject,message,[email],owner.email,att)