from django.conf import settings
import boto
from boto.s3.key import Key
from django.core.mail import send_mail, EmailMessage
import pprint
from django.core.files.storage import default_storage
import os

FROM_VIAM_EMAIL = getattr(settings, "FROM_VIAM_EMAIL", None)
ENABLE_EMAIL_SANDBOX = getattr(settings, "ENABLE_EMAIL_SANDBOX", None)

Email_footer = '<br/><br/>Best Regards,<br/>Team ViamHealth'

def send_mail(subject, message, recipient_list, from_email=None, attachment=None ):
	html_message = True
	if ENABLE_EMAIL_SANDBOX is not None and ENABLE_EMAIL_SANDBOX == True:
		recipient_list = ['kunal.rachhoya@viamhealth.com','Narendra.Mudigal@viamhealth.com',]

	try:
		if from_email is None:
			from_email = FROM_VIAM_EMAIL

		email = EmailMessage(subject, message, from_email, recipient_list)

		if attachment is not None:
			
			LOCAL_PATH = settings.S3_LOCAL_DOWNLOAD_LOCATION

			conn = boto.connect_s3(settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
			key = conn.get_bucket(settings.AWS_STORAGE_BUCKET_NAME).get_key(attachment.get('url'))

			if os.path.exists(LOCAL_PATH+attachment.get('name')):
				os.remove(LOCAL_PATH+attachment.get('name'))
			key.get_contents_to_filename(LOCAL_PATH+attachment.get('name'))
			att = file(LOCAL_PATH+attachment.get('name'),'r')
			if att:
				email.attach(attachment.get('name'), att.read())
			else:
				pass
			
		if html_message:
		    email.content_subtype = 'html'
		email.send()
		return True
	except Exception as e:
		print '%s (%s)' % (e.message, type(e))
		return False

def signup_email(email):
	subject = 'Welcome to a Healthy Future by ViamHealth'
	message = 'Thank You for registering with us.<br/><br/>Please provide us with any feedback on feedback@viamhealth.com.<br/><br/>We wish you and your family a healthy future.' + Email_footer
	send_mail(subject, message, [email])

def invite_new_email(invited, inviter, password):
	email = invited.email
	subject = 'Have a Healthy Future'
	message = 'Hello,<br/><br/>You have been invited to have a Healthy Future with ViamHealth being your health assistant.<br/><br/>Your registration details -Y<br/><br/>UserName: ' + str(email) + '<br/><br/>Password(autogenerated): '+ password + '<br/><br/>Please change the password as soon as you login.<br/><br/>Please do provide us with any feedback on feedback@viamhealth.com.<br/><br/>We wish you and your family a healthy future.'+ Email_footer
	send_mail(subject, message, [email])

def invite_existing_email(invited, inviter):
	email = invited.email
	subject = 'Have a Healthy Future'
	message = 'Hello,<br/><br/>You have been invited to have a Healthy Future with ViamHealth being your health assistant.<br/><br/>Your registration details -Y<br/><br/>UserName: ' + str(email) + '<br/><br/>Please do provide us with any feedback on feedback@viamhealth.com.<br/><br/>We wish you and your family a healthy future.'+ Email_footer
	send_mail(subject, message, [email])

def forgot_password_email(user,password):
	name = ' '
	if user.first_name is not None and str(user.first_name) != '':
		name = ' '+str(user.first_name)

	email_str = ''
	if user.email is not None:
		email_str = 'UserName: '+user.email + '<br/><br/>'

	email = user.email
	subject = 'New Password Generated'
	message = 'Hello'+name',<br/><br/>As per your request we have generated a new password for you to access ViamHealth.<br/><br/>You registration details -<br/><br/>'+email_str+'New Password(autogenerated): '+ password +'<br/><br/>Please change the password as soon as you login.<br/><br/>Please do provide us with any feedback on feedback@viamhealth.com.<br/><br/>We wish you and your family a healthy future.' + Email_footer
	send_mail(subject, message, [email])

def share_user_email(invited, inviter, share_user):
	inviter_name_str = ''
	
	if inviter.first_name is not None and str(inviter.first_name) != '':
		inviter_name_str =  str(inviter.first_name)

	invited_name_str = ''
	
	if invited.first_name is not None and str(invited.first_name) != '':
		invited_name_str = ' '+ str(invited.first_name)
	"""
	shared_of = ''
	if share_user.first_name is not None and str(share_user.first_name) != '':
		shared_of = 'of '+ str(share_user.first_name)
	"""
	email = invited.email

	subject = inviter_name_str + 'is sharing his/her health profile with you'
	message = 'Hello '+invited_name_str+',<br/><br/>'+inviter_name_str+' wants to share his/her health profile. Once you accept his invitation he/ she will also get access to your health profile.<br/><br/>We wish both of you a healthy future.<br/><br/>Please do provide us with any feedback on feedback@viamhealth.com.'+Email_footer
	inv_email = None
	if inviter.email is not None:
		inv_email = inviter.email
	send_mail(subject, message, [email], inv_email)

def share_healthfile_email(owner, email,att):
	
	email = email
	if owner.first_name is not None and owner.first_name != '':
		subject = owner.first_name + ' shared a file with you via ViamHealth'
	else:
		subject = 'File shared with you via ViamHealth'

	message = 'Please find the file attached with this email.'
	inv_email = None
	if owner.email is not None:
		inv_email = owner.email
	
	send_mail(subject,message,[email],owner.email,att)
